#!/bin/bash

_set_doge () {
    ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "
              ⏳ STARTING ⏳
        '''''''''''''''''''''''''''
            🐶 DOGE USERBOT 🐾
    "
    python3 doger.py
}

_set_doge
